### ISSUE TITLE
EPIC: Expand test coverage

### ISSUE THREAD

**Issue by mikemonteith** [nhsuk/wagtail-nhsuk-frontend#150]
- [x] Form Template Tags #205 
- [x] Component Template Tags #206 
- [x] Blocks #207

**Comment by magicaljellybeans** [comment]
Tests needed for:
_formtemplates/tags:_
- [ ] def nhsuk_form()
- [ ] def add_class()
- [ ] def get_widget_html_class()
- [ ] def get_widget_html_error_class()
- [ ] def add_widget_classes()
- [ ] def is_checkbox()

_templates/tags:_
- [ ] def pagination()
- [ ] def chunk()
- [ ] def promo_group_column_class()

_template/blocks:_
- [ ] class FlattenValueContext/def get_context
- [ ] class ActionLinkBlock/def clean
- [ ] class CareCardBlock/def get_context

**Comment by magicaljellybeans** [comment]
Closed with #208
