### ISSUE TITLE
EPIC: Progress monitoring for wagtail-nhsuk-frontend v1.0.0

### ISSUE THREAD

**Issue by DomBaker** [nhsuk/wagtail-nhsuk-frontend#200]
- [x] Removal of redundant components #194
- [x] Add Forms #202 
- [x] Add Tables #23 
- [x] Write up documentation for new components
- [x] Improve test coverage #150 
- [x] Update documentation regarding the upgrade procedure #211

**Comment by magicaljellybeans** [comment]
v1 now released!
